/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 26 19:12:50 GMT 2019
 */

package com.repoMiner;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.repoMiner.Main;
import java.io.EOFException;
import java.io.FileNotFoundException;
import java.io.IOException;
import org.codehaus.plexus.util.xml.pull.XmlPullParserException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Main_ESTest extends Main_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/home/suntrie/IdeaProjects/testable/pom.xml");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "R>7KL@rjKx'3v3");
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: XmlPullParserException");
      
      } catch(Throwable e) {
         //
         // only whitespace content allowed before start tag and not R (position: START_DOCUMENT seen R... @1:1) 
         //
         verifyException("org.codehaus.plexus.util.xml.pull.MXParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/home/suntrie/IdeaProjects/testable/pom.xml");
      FileSystemHandling.shouldThrowIOException(evoSuiteFile0);
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "^ [h5y{?gS'wNG1Buo");
      String[] stringArray0 = new String[3];
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[5];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/home/suntrie/IdeaProjects/testable/pom.xml");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: EOFException");
      
      } catch(EOFException e) {
         //
         // no more data available START_DOCUMENT seen \\n... @2:1
         //
         verifyException("org.codehaus.plexus.util.xml.pull.MXParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[1];
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Main main0 = new Main();
  }
}
